image:
  file: .gitpod.dockerfile
ports:
  - port: 1080
    onOpen: notify
  - port: 1081
    onOpen: notify
  - port: 6080
    onOpen: open-browser
  - port: 8080
    onOpen: ignore
  - port: 8088
    onOpen: ignore    
checkoutLocation: "go/src/github.com/xuiv/xuiv.github.io"
workspaceLocation: "go/src/github.com/xuiv/xuiv.github.io"
tasks:
  - init: >
      clear
    command: >
      python ad.py &
github:
    prebuilds:
        pullRequestsFromForks: true
