image:
  file: .gitpod.dockerfile
ports:
  - port: 1080
    onOpen: notify
  - port: 1081
    onOpen: notify
  - port: 6080
    onOpen: notify
    onOpen: notify
  - port: 8080
    onOpen: notify
checkoutLocation: "go/src/github.com/xuiv/xuiv.github.io"
workspaceLocation: "go/src/github.com/xuiv/xuiv.github.io"
tasks:
  - init: >
      clear
github:
    prebuilds:
        pullRequestsFromForks: true
